set(CMAKE_BUILD_TYPE        "Debug" CACHE STRING "")

set(QPMAD_BUILD_TESTS       "ON"    CACHE STRING "")
set(QPMAD_ENABLE_TRACING    "ON"    CACHE STRING "")
set(QPMAD_CPP_SANITIZERS    "ON"    CACHE STRING "")
set(QPMAD_CLANG_TIDY        "ON"    CACHE STRING "")
