on:
    push:
        branches:
            - '**'
    pull_request:
        types: [opened, reopened]


env:
    APT: sudo apt install -y --no-install-recommends

jobs:
    cpp_octave:
        runs-on: ubuntu-22.04
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt update
            - run: make install_deps_common
            - run: $APT libboost-all-dev libeigen3-dev octave liboctave-dev
            - run: $APT clang-tidy-13
            - run: make test

    latest_eigen:
        runs-on: ubuntu-22.04
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - run: sudo apt update
            - run: make install_deps_common
            - run: $APT libboost-all-dev octave liboctave-dev
            - run: $APT clang-tidy-13
            - run: make install_latest_eigen
            # suppressions needed for sanitizers
            - run: make unit_tests OPTIONS=test

    dependency:
        runs-on: ubuntu-22.04
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - run: $APT libeigen3-dev
            - run: make build
            - run: sudo make install
            - run: make test_dependency

    focal_noetic_catkin_old:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_old ROS_DISTRO=noetic UBUNTU_DISTRO=focal

    focal_noetic_catkin_new:
        container: ros:noetic-ros-base-focal
        runs-on: ubuntu-latest
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - run: |
                source /opt/ros/noetic/setup.bash
                make catkin_test_new ROS_DISTRO=noetic UBUNTU_DISTRO=focal

    jammy_scanbuild:
        runs-on: ubuntu-22.04

        steps:
            - uses: actions/checkout@v4
            - run: sudo apt update
            - run: $APT libboost-all-dev libeigen3-dev octave liboctave-dev
            - run: $APT clang-tidy-13
            - run: make clangcheck SCANBUILD=scan-build-13

    deb:
        runs-on: ubuntu-22.04
        defaults:
            run:
                shell: bash
        steps:
            - uses: actions/checkout@v4
            - run: $APT libeigen3-dev
            - run: make deb_install_deps
            - run: make deb_any
            - run: sudo dpkg -i build/qpmad-*-any.deb
            - run: make test_dependency
            - uses: actions/upload-artifact@v4
              with:
                  name: deb
                  path: build/qpmad-*-any.deb

    msvc:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4
            - uses: ilammy/msvc-dev-cmd@v1
              with:
                  arch: x64
            - run: |
                  cmake -D VCPKG_INSTALL_OPTIONS="--x-feature=test" -D CMAKE_TOOLCHAIN_FILE=C:\vcpkg\scripts\buildsystems\vcpkg.cmake -D QPMAD_BUILD_TESTS=ON -G "NMake Makefiles" .
                  nmake
            - run: ctest --schedule-random --output-on-failure

    jammy_ccws_static:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                path: src/qpmad
            - run: make bp_install_build BUILD_PROFILE=scan_build
            - run: make bp_install_build BUILD_PROFILE=static_checks
            - run: make BUILD_PROFILE=static_checks
            - run: make dep_install PKG=qpmad
            - run: make qpmad BUILD_PROFILE=scan_build

    jammy_ccws_plain:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                path: src/qpmad
            - run: make bp_install_build BUILD_PROFILE=reldebug
            - run: make dep_install PKG=qpmad
            - run: make qpmad
            - run: make test PKG=qpmad

    jammy_ccws_threadsan:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                path: src/qpmad
            - run: make bp_install_build BUILD_PROFILE=thread_sanitizer
            - run: make dep_install PKG=qpmad
            - run: make qpmad BUILD_PROFILE=thread_sanitizer
            - run: make test PKG=qpmad BUILD_PROFILE=thread_sanitizer

    jammy_ccws_asan:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v4
              with:
                repository: asherikov/ccws
            - uses: actions/checkout@v4
              with:
                path: src/qpmad
            - run: make bp_install_build BUILD_PROFILE=addr_undef_sanitizers
            - run: make dep_install PKG=qpmad
            - run: make qpmad BUILD_PROFILE=addr_undef_sanitizers
            - run: make test PKG=qpmad BUILD_PROFILE=addr_undef_sanitizers
